@startuml
'https://plantuml.com/class-diagram


interface GetPropStrategy{
+ doGetprop(AbstractEnemy abstractEnemy):List<AbstractProp>
}

abstract  class AbstractEnemy{
- getPropStrategy:GetPropStrategy
+ AbstractEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
+ shoot():List<BaseBullet>
+ getProp():AbstractProp
+ setGetPropStrategy(GetPropStrategy getPropStrategy)
}

class RandomPropStrategy{
- seed:double
+ doGetprop(AbstractEnemy abstractEnemy):List<AbstractProp>
}

class BossPropStrategy{
- propnum:int
+ doGetprop(AbstractEnemy abstractEnemy):List<AbstractProp>
}

class Game{}

Game ..> AbstractEnemy
AbstractEnemy o-down-> GetPropStrategy
RandomPropStrategy .up.|> GetPropStrategy
BossPropStrategy .up.|> GetPropStrategy

@enduml