@startuml
'https://plantuml.com/class-diagram

interface UserDao{
   + getAllUsers(): List<User>
   + addUser(User user)
   + makerand()
   + delete(int num)
   + dosave()
   + doload()
}

class UserDaolmpl{
   - users:List <User>
   + getAllUsers(): List<User>
   + addUser(User user)
   + makerand()
   + delete(int num)
   + dosave()
   + doload()
}

class User{
    - userscore:int
    - username:String
    - useraddtime:String
    + User(String username, int userscore,String addtime)
    + getUserscore():int
    + getUsername():String
    + getAddtime():String
    + toString():String
}

class Game{
 + setUserDaoAction()
}

class Simpletable{
}

Game .right.> UserDao
Simpletable .left.>UserDao
UserDaolmpl .up.|> UserDao
UserDaolmpl -left-> User

@enduml