@startuml
'https://plantuml.com/class-diagram

abstract class AbstractAircraft
{
	# axHp:int
    # hp:int
    # direction:int
    # shoot_freq:int
    - shootStrategy:ShootStrategy
    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp,int shoot_freq)
    + decreaseHp(int decrease)
    + getHp():int
    + shoot():List<BaseBullet>
    + getdirection():int
    + setShootStrategy(ShootStrategy shootStrategy)
 }


interface ShootStrategy
{
  +doshoot(AbstractAircraft abstractAircraft):List<BaseBullet>
}

class RandomShootStrategy
{
  -shootNum:int
  -power:int
  -freq_control:int
  -cnt:int
  +RandomShootStrategy(int power,int freq_control)
  +doshoot(AbstractAircraft abstractAircraft):List<BaseBullet>
}

class StraightShootStrategy
{
  -shootNum:int
  -power:int
  -freq_control:int
  -cnt:int
  +StraightShootStrategy(int power,int freq_control)
  +doshoot(AbstractAircraft abstractAircraft):List<BaseBullet>
}

class Game{
}

Game ..> AbstractAircraft
AbstractAircraft o-down-> ShootStrategy
StraightShootStrategy .up.|> ShootStrategy
RandomShootStrategy .up.|> ShootStrategy


@enduml